#ifndef SONG_NATIONAL_ANTHEM
#define SONG_NATIONAL_ANTHEM

const note_t song_national_anthem[] = {{PERIOD(392), 250 + 125},
                                       {PERIOD(329), 125},
                                       {PERIOD(261), 500},
                                       {PERIOD(329), 500},
                                       {PERIOD(392), 500},
                                       {PERIOD(523), 1000},
                                       {PERIOD(659), 250 + 125},
                                       {PERIOD(587), 125},
                                       {PERIOD(523), 500},
                                       {PERIOD(329), 500},
                                       {PERIOD(369), 500},
                                       {PERIOD(392), 995},
                                       {0, 5},
                                       {PERIOD(392), 245},
                                       {0, 5},
                                       {PERIOD(392), 250},
                                       {PERIOD(659), 500 + 250},
                                       {PERIOD(587), 250},
                                       {PERIOD(523), 500},
                                       {PERIOD(493), 1000},
                                       {PERIOD(440), 250 + 125},
                                       {PERIOD(493), 125},
                                       {PERIOD(523), 495},
                                       {0, 5},
                                       {PERIOD(523), 500},
                                       {PERIOD(392), 500},
                                       {PERIOD(329), 500},
                                       {PERIOD(261), 500},
                                       {PERIOD(392), 250 + 125},
                                       {PERIOD(329), 125},
                                       {PERIOD(261), 500},
                                       {PERIOD(329), 500},
                                       {PERIOD(392), 500},
                                       {PERIOD(523), 1000},
                                       {PERIOD(659), 250 + 125},
                                       {PERIOD(587), 125},
                                       {PERIOD(523), 500},
                                       {PERIOD(329), 500},
                                       {PERIOD(369), 500},
                                       {PERIOD(392), 995},
                                       {0, 5},
                                       {PERIOD(392), 245},
                                       {0, 5},
                                       {PERIOD(392), 250},
                                       {PERIOD(659), 500 + 250},
                                       {PERIOD(587), 250},
                                       {PERIOD(523), 500},
                                       {PERIOD(493), 1000},
                                       {PERIOD(440), 250 + 125},
                                       {PERIOD(493), 125},
                                       {PERIOD(523), 495},
                                       {0, 5},
                                       {PERIOD(523), 500},
                                       {PERIOD(392), 500},
                                       {PERIOD(329), 500},
                                       {PERIOD(261), 500},
                                       {PERIOD(659), 245},
                                       {0, 5},
                                       {PERIOD(659), 245},
                                       {0, 5},
                                       {PERIOD(659), 500},
                                       {PERIOD(698), 500},
                                       {PERIOD(783), 495},
                                       {0, 5},
                                       {PERIOD(783), 1000},
                                       {PERIOD(698), 250},
                                       {PERIOD(659), 250},
                                       {PERIOD(587), 500},
                                       {PERIOD(659), 500},
                                       {PERIOD(698), 495},
                                       {0, 5},
                                       {PERIOD(698), 995},
                                       {0, 5},
                                       {PERIOD(698), 500},
                                       {PERIOD(659), 500 + 250},
                                       {PERIOD(587), 250},
                                       {PERIOD(523), 500},
                                       {PERIOD(493), 1000},
                                       {PERIOD(440), 250 + 125},
                                       {PERIOD(493), 125},
                                       {PERIOD(523), 500},
                                       {PERIOD(329), 500},
                                       {PERIOD(369), 500},
                                       {PERIOD(392), 995},
                                       {0, 5},
                                       {PERIOD(392), 500},
                                       {PERIOD(523), 495},
                                       {0, 5},
                                       {PERIOD(523), 495},
                                       {0, 5},
                                       {PERIOD(523), 250},
                                       {PERIOD(493), 250},
                                       {PERIOD(440), 495},
                                       {0, 5},
                                       {PERIOD(440), 495},
                                       {0, 5},
                                       {PERIOD(440), 500},
                                       {PERIOD(587), 500},
                                       {PERIOD(698), 250},
                                       {PERIOD(659), 250},
                                       {PERIOD(587), 250},
                                       {PERIOD(523), 245},
                                       {0, 5},
                                       {PERIOD(523), 500},
                                       {PERIOD(493), 500},
                                       {PERIOD(392), 245},
                                       {0, 5},
                                       {PERIOD(392), 250},
                                       {PERIOD(523), 500 + 250},
                                       {PERIOD(587), 250},
                                       {PERIOD(659), 250},
                                       {PERIOD(698), 250},
                                       {PERIOD(783), 1000},
                                       {PERIOD(523), 250},
                                       {PERIOD(587), 250},
                                       {PERIOD(659), 500 + 250},
                                       {PERIOD(698), 250},
                                       {PERIOD(587), 500},
                                       {PERIOD(523), 1000},
                                       {0, 0}};

#endif
