Import('*')

# build gtest
gtest_main_a = '#/test/gtest/make/gtest_main.a'
build_gtest = env.Command(gtest_main_a, '', 'cd test/gtest/make; make')
rename_gtest = env.Command('#/test/gtest/make/libgtest.a', gtest_main_a, 'cd test/gtest/make; ln -s gtest_main.a libgtest.a')

# add all test .cpp files here
test_srcs = [
	'example_test.cpp'
]

env.Append(LIBS=['gtest'])
env.Append(LIBPATH=['#/test/gtest/make'])
env.Append(CPPPATH=['#/test/gtest/include'])

# build the program that runs the tests
test_runner = env.Program('test-runner', test_srcs)
env.Depends(test_runner, rename_gtest);
install_test_runner = env.Install(exec_dir, test_runner)

# make a 'test' command so that 'scons test' builds the tests and runs them
test = env.Command('fasdfdasfdsfdsfdasf',
	exec_dir.File('test-runner'),
	'%s' % exec_dir.File('test-runner'))
AlwaysBuild(test)
env.Depends(test, install_test_runner)
env.Depends(test, test_runner)
