Import('*')

e = env.Clone()

e.Append(CPPPATH=['/usr/include/bullet'])

# Find uic output
e.Append(CPPPATH='.')

p = e.Program('simulator', [
	'main.cpp',
	'SimControl.cpp',
	'Config.cpp',
	'Physics/Env.cpp',
	'Physics/Entity.cpp',
	'Physics/Ball.cpp',
	'Physics/Field.cpp',
	'Physics/Robot.cpp'])

uics = e.Uic4([
	'SimControl.ui'
])
e.Depends(p, uics)

e.Append(LIBS=['BulletCollision', 'BulletDynamics'])

Default(e.Install(exec_dir, p))
Help('simulator: Provides simulation of SSL robots, using Bullet Physics\n')

