Import('*')

env.Append(PHYSX_SDK='/usr/include/PhysX/v2.8.1/SDKs')
env.Append(CPPPATH=[
	'$PHYSX_SDK/Physics/include',
	'$PHYSX_SDK/Foundation/include',
	'$PHYSX_SDK/PhysXLoader/include',
	'$PHYSX_SDK/Cooking/include'])

env.Append(LIBPATH='/usr/lib/PhysX/v2.8.1')
env.MergeFlags('-DNX32 -DLINUX -DNX_DISABLE_FLUIDS')

env.Append(LIBS=['NxCooking', 'PhysXLoader'])

p = env.Program('soccsim', [
	'main.cpp',
	'Viewer.cpp',
	'Config.cpp',
	'Physics/Env.cpp',
	'Physics/Entity.cpp',
	'Physics/Ball.cpp',
	'Physics/Field.cpp',
	'Physics/Robot.cpp',
	'Physics/MemoryStream.cpp'])

env.Install(exec_dir, p)
