<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>rj_control</name>
  <version>0.0.0</version>
  <description>TODO: Package description</description>
  <maintainer email="n8.wert.b@gmail.com">n8w3rt</maintainer>
  <license>TODO: License declaration</license>

  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>flann</depend>
  <depend>eigen3_cmake_modules</depend>
  <depend>rj_control_msgs</depend>

  <depend>rj_utils</depend>
  <depend>rj_constants</depend>
  <depend>rj_msgs</depend>
  <depend>rj_param_utils</depend>
  <depend>rj_topic_utils</depend>
  <depend>rj_common</depend>
  <depend>rj_geometry</depend>
  <depend>rj_convert</depend>
  <depend>rj_control_extensions</depend>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <test_depend>ament_cmake_gtest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
