formatters:
    .py: yapf
    .h: clang
    .hpp: clang
    .c: clang
    .cc: clang
    .cpp: clang
formatter_args:
    clang:
        - --style=file
    yapf:
        - --style=.style.yapf
exclude:
    - build
    - external
    - old
