
language: objective-c

before_install:
  - brew remove --force $(brew list)
  - util/osx-setup

cache:
  directories:
    - $HOME/.ccache
    - /usr/local

script: make

notifications:
  email: false
