language: cpp
compiler: clang

submodules: false

before_install:
  # we have to get the games PPA so we can install libbullet-dev
  - wget -q -O - http://archive.getdeb.net/getdeb-archive.key | sudo apt-key add -
  - sudo sh -c 'echo "deb http://archive.getdeb.net/ubuntu raring-getdeb games" >> /etc/apt/sources.list.d/getdeb.list'

  # we use boost python 3.3, but ubuntu12.04 (which travis uses as of now) has an older version
  # we get around this by using 'apt-pinning' to get this package from a newer ubuntu repo
  # see this link for more info: http://askubuntu.com/questions/103320/install-packages-from-newer-release-without-building-apt-pinning
  - echo sudo echo "Package: libboost*\nPin: release n=saucy\nPin-Priority: 990\n" >> /etc/apt/preferences
  - echo sudo echo "Package: python*\nPin: release n=saucy\nPin-Priority: 990\n" >> /etc/apt/preferences
  - echo "deb http://archive.ubuntu.com/ubuntu/ saucy main" > /etc/apt/sources.list.d/saucy.list

  - sudo apt-get update

  - sudo ./util/ubuntu-setup

script: scons && scons test

notifications:
  email: false
