
language: objective-c
osx_image: xcode7

# only run travis-ci on master
branches:
  only:
    - master

before_install:
  - travis_wait brew update > brew-update.log
  - travis_wait brew upgrade > brew-upgrade.log
  - util/osx-setup

cache:
  directories:
    - $HOME/.ccache
    - /usr/local

script:
    - make
    - make robot2015
    - make kicker2015
    - make base2015

notifications:
  email: false
