
language: objective-c

# only run travis-ci on master
branches:
  only:
    - master

before_install:
  - brew update > brew-update.log
  - brew upgrade > brew-upgrade.log
  - util/osx-setup

cache:
  directories:
    - $HOME/.ccache
    - /usr/local

script: make

notifications:
  email: false
