# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ssl_simulation_config.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ssl_simulation_config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ssl_gc_common_pb2 as ssl__gc__common__pb2
import ssl_vision_geometry_pb2 as ssl__vision__geometry__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bssl_simulation_config.proto\x1a\x13ssl_gc_common.proto\x1a\x19ssl_vision_geometry.proto\x1a\x19google/protobuf/any.proto\"\xc2\x01\n\x0bRobotLimits\x12 \n\x18\x61\x63\x63_speedup_absolute_max\x18\x01 \x01(\x02\x12\x1f\n\x17\x61\x63\x63_speedup_angular_max\x18\x02 \x01(\x02\x12\x1e\n\x16\x61\x63\x63_brake_absolute_max\x18\x03 \x01(\x02\x12\x1d\n\x15\x61\x63\x63_brake_angular_max\x18\x04 \x01(\x02\x12\x18\n\x10vel_absolute_max\x18\x05 \x01(\x02\x12\x17\n\x0fvel_angular_max\x18\x06 \x01(\x02\"b\n\x10RobotWheelAngles\x12\x13\n\x0b\x66ront_right\x18\x01 \x02(\x02\x12\x12\n\nback_right\x18\x02 \x02(\x02\x12\x11\n\tback_left\x18\x03 \x02(\x02\x12\x12\n\nfront_left\x18\x04 \x02(\x02\"\xa1\x02\n\nRobotSpecs\x12\x14\n\x02id\x18\x01 \x02(\x0b\x32\x08.RobotId\x12\x14\n\x06radius\x18\x02 \x01(\x02:\x04\x30.09\x12\x14\n\x06height\x18\x03 \x01(\x02:\x04\x30.15\x12\x0c\n\x04mass\x18\x04 \x01(\x02\x12\x1d\n\x15max_linear_kick_speed\x18\x07 \x01(\x02\x12\x1b\n\x13max_chip_kick_speed\x18\x08 \x01(\x02\x12\x1a\n\x12\x63\x65nter_to_dribbler\x18\t \x01(\x02\x12\x1c\n\x06limits\x18\n \x01(\x0b\x32\x0c.RobotLimits\x12\'\n\x0cwheel_angles\x18\r \x01(\x0b\x32\x11.RobotWheelAngles\x12$\n\x06\x63ustom\x18\x0e \x01(\x0b\x32\x14.google.protobuf.Any\"5\n\rRealismConfig\x12$\n\x06\x63ustom\x18\x01 \x01(\x0b\x32\x14.google.protobuf.Any\"\x95\x01\n\x0fSimulatorConfig\x12#\n\x08geometry\x18\x01 \x01(\x0b\x32\x11.SSL_GeometryData\x12 \n\x0brobot_specs\x18\x02 \x03(\x0b\x32\x0b.RobotSpecs\x12&\n\x0erealism_config\x18\x03 \x01(\x0b\x32\x0e.RealismConfig\x12\x13\n\x0bvision_port\x18\x04 \x01(\rB8Z6github.com/RoboCup-SSL/ssl-simulation-protocol/pkg/sim')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ssl_simulation_config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z6github.com/RoboCup-SSL/ssl-simulation-protocol/pkg/sim'
  _globals['_ROBOTLIMITS']._serialized_start=107
  _globals['_ROBOTLIMITS']._serialized_end=301
  _globals['_ROBOTWHEELANGLES']._serialized_start=303
  _globals['_ROBOTWHEELANGLES']._serialized_end=401
  _globals['_ROBOTSPECS']._serialized_start=404
  _globals['_ROBOTSPECS']._serialized_end=693
  _globals['_REALISMCONFIG']._serialized_start=695
  _globals['_REALISMCONFIG']._serialized_end=748
  _globals['_SIMULATORCONFIG']._serialized_start=751
  _globals['_SIMULATORCONFIG']._serialized_end=900
# @@protoc_insertion_point(module_scope)
