# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ssl_simulation_robot_feedback.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ssl_simulation_robot_feedback.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ssl_simulation_error_pb2 as ssl__simulation__error__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#ssl_simulation_robot_feedback.proto\x1a\x1assl_simulation_error.proto\x1a\x19google/protobuf/any.proto\"`\n\rRobotFeedback\x12\n\n\x02id\x18\x01 \x02(\r\x12\x1d\n\x15\x64ribbler_ball_contact\x18\x02 \x01(\x08\x12$\n\x06\x63ustom\x18\x03 \x01(\x0b\x32\x14.google.protobuf.Any\"Y\n\x14RobotControlResponse\x12\x1f\n\x06\x65rrors\x18\x01 \x03(\x0b\x32\x0f.SimulatorError\x12 \n\x08\x66\x65\x65\x64\x62\x61\x63k\x18\x02 \x03(\x0b\x32\x0e.RobotFeedbackB8Z6github.com/RoboCup-SSL/ssl-simulation-protocol/pkg/sim')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ssl_simulation_robot_feedback_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z6github.com/RoboCup-SSL/ssl-simulation-protocol/pkg/sim'
  _globals['_ROBOTFEEDBACK']._serialized_start=94
  _globals['_ROBOTFEEDBACK']._serialized_end=190
  _globals['_ROBOTCONTROLRESPONSE']._serialized_start=192
  _globals['_ROBOTCONTROLRESPONSE']._serialized_end=281
# @@protoc_insertion_point(module_scope)
