# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ssl_gc_common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ssl_gc_common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13ssl_gc_common.proto\"*\n\x07RobotId\x12\n\n\x02id\x18\x01 \x01(\r\x12\x13\n\x04team\x18\x02 \x01(\x0e\x32\x05.Team*)\n\x04Team\x12\x0b\n\x07UNKNOWN\x10\x00\x12\n\n\x06YELLOW\x10\x01\x12\x08\n\x04\x42LUE\x10\x02*1\n\x08\x44ivision\x12\x0f\n\x0b\x44IV_UNKNOWN\x10\x00\x12\t\n\x05\x44IV_A\x10\x01\x12\t\n\x05\x44IV_B\x10\x02\x42?Z=github.com/RoboCup-SSL/ssl-game-controller/internal/app/state')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ssl_gc_common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z=github.com/RoboCup-SSL/ssl-game-controller/internal/app/state'
  _globals['_TEAM']._serialized_start=67
  _globals['_TEAM']._serialized_end=108
  _globals['_DIVISION']._serialized_start=110
  _globals['_DIVISION']._serialized_end=159
  _globals['_ROBOTID']._serialized_start=23
  _globals['_ROBOTID']._serialized_end=65
# @@protoc_insertion_point(module_scope)
