#!/usr/bin/python

from watchdog import *

wd = watchdog(form.getvalue('host'))

cmd = form.getvalue('cmd')
proc = form.getvalue('proc')
arg = form.getvalue('arg')

if cmd == None:
    raise RuntimeError, 'No command specified'

line = cmd
if proc != None:
    line += ' ' + escape(proc)
if arg != None:
    line += ' ' + escape(arg)

wd.command(line)

print 'Location: ' + get_param('ret', 'status')
print ''
