#!/usr/bin/python

from watchdog import *

group_name = form.getvalue('group')
if group_name == None:
    raise RuntimeError, 'No group specified'

group = process_groups[group_name]

for pg_host in group:
    # pg_host is a (host, [processes]) tuple
    
    host = pg_host[0]
    wd = watchdog(host)
    
    for proc in pg_host[1]:
        wd.command('disable ' + escape(proc))
        
        try:
            wd.command('signal ' + escape(proc) + ' 15')
        except:
            pass
    
    wd.close()

print 'Location: ' + get_param('ret', 'groups')
print ''
