#!/usr/bin/python

from watchdog import *

wd = watchdog(form.getvalue('host'))
status = wd.process_status()

for proc in status:
    eproc = escape(proc)
    
    if status[proc]['enabled'] == '1' and status[proc]['running'] == '0':
        wd.command('start ' + eproc + ' ' + remote_addr)

print 'Location: ' + get_param('ret', 'status')
print ''
