#!/usr/bin/python

import sys
from robocup_log import *
from LogFrame_pb2 import *

if len(sys.argv) != 2:
	print >> sys.stderr, 'Usage: %s <input.log>' % sys.argv[0]
	sys.exit(1)

log = RobocupLog(sys.argv[1])

frame = log.readFrame()
if frame.HasField('log_config'):
	print frame.log_config
else:
	print 'No log config'

