Import('*')

p = env.Program('convert_tcpdump',
	['convert_tcpdump.cpp'],
	LIBS=['pcap', 'protobuf', 'pthread', 'common'])
Default(env.Install(exec_dir, p))
Help('convert_tcpdump: Converts a tcpdump log to a soccer (protobuf) log\n')

p = env.Program('simple_logger',
	['simple_logger.cpp'])
Default(env.Install(exec_dir, p))
Help('simple_logger: Stand-alone log recorder (vision and referee only)\n')

# This has to be copied, not symlinked, because python will look in the file's
# real location for modules, but we need generated protobuf files to be in
# exec_dir.
env.Install(exec_dir, 'log_info')
env.Install(exec_dir, 'robocup_log.py')
