#!/usr/bin/env python
# -*- coding: utf-8 -*-

# FIXME - Firmware is broken.  This doesn't actually work, but it's not this script's fault.

import usb
import sys

h = None
for bus in usb.busses():
	for dev in bus.devices:
		if dev.idVendor == 0x3141 and dev.idProduct == 0x0004:
			h = dev.open()

if not h:
	print 'No base station found'
	sys.exit(1)

h.controlMsg(0x40, 0xff, '')
