#!/usr/bin/env python

import sys

if len(sys.argv) != 3:
	print >> sys.stderr, 'Usage: %s <robot ID> <kick strength>' % sys.argv[0]
	sys.exit(1)

from rc_radio import *

forward = [0] * 36
forward[1 + 4] = int(sys.argv[1]);
forward[1 + 5] = int(sys.argv[2]);
forward[1 + 6] = 0x02;

send(forward)
