#!/usr/bin/env python

from math import *
from numpy import *
from matplotlib.pyplot import *
from motor_model import *

# Max steady-state speed is 564.02

motor = MotorModel()
motor.cmd = 127

# Load reference data
ref = loadtxt('data/%d_bench' % motor.cmd)
ref_vbatt = ref[2:,0]
ref_enc_delta = ref[2:,1]

n = len(ref_vbatt)
#n = 50

motor.vbatt = ref[0,0]

s = []
#motor.angle = -0.8		# 15_batt
#motor.angle = -2.1		# 63_batt
#motor.angle = -1.4		# 127_batt
#motor.load = 160		# 127_batt
motor.angle = -1.5		# 127_bench
motor.load = 130		# 127_bench
motor.kr = 379			# 127_bench
motor.friction = 0
#motor.kosc = 0
for i in range(n):
	motor.step()
	s.append(motor.enc_delta)
	#print '%6.3f %3d %6.3f %3d %3d' % (vs, enc_delta, ref_vbatt[i], ref_enc_delta[i], enc_delta - ref_enc_delta[i])

#for i in range(n):
	#print s[i], int(ref_enc_delta[i])
plot(s, 'b', ref_enc_delta[:n], 'r')
show()
