#!/usr/bin/python

from watchdog import *

wd = watchdog(form.getvalue("host"))

name = form.getvalue("name")
if name == None:
    raise RuntimeError, "No process given"
ename = escape(name)

status = wd.process_status(name)

if not status.has_key(name):
    raise RuntimeError, "No such process"

props = status[name]

new_name = form.getvalue("new_name")
if new_name == None or new_name == "":
    raise RuntimeError, "Can't remove a process's name"
if new_name != name and status.has_key(new_name):
    raise RuntimeError, "A different process with the new name already exists"
if new_name != name:
    enew_name = escape(new_name)
    wd.command("rename " + ename + " " + enew_name)
    ename = enew_name

cwd = form.getvalue("cwd")
if cwd == None:
    cwd = "."
if cwd != props["cwd"]:
    wd.command("cwd " + ename + " " + escape(cwd))

command = form.getvalue("command")
if command == None:
    raise RuntimeError, "No command given"
if command != props["command"]:
    wd.command("command " + ename + " " + command)

enabled = form.getvalue("enabled")
if props["enabled"] == "1" and enabled != "on":
    wd.command("disable " + ename)
if props["enabled"] == "0" and enabled == "on":
    wd.command("enable " + ename)

delay = form.getvalue("delay")
if delay == None:
    delay = "0"
if delay != props["delay"]:
    wd.command("delay " + ename + " " + delay)

max_restarts = form.getvalue("max_restarts")
if max_restarts == None:
    max_restarts = "0"
if max_restarts != props["max_restarts"]:
    wd.command("max_restarts " + ename + " " + max_restarts)

if form.getvalue("auto_display") == "on":
    auto_display = "1"
else:
    auto_display = "0"
if props["auto_display"] != auto_display:
    wd.command("auto_display " + ename + " " + auto_display)

display = form.getvalue("display")
if display == None:
    display = ""
if display != props["display"]:
    wd.command("display " + ename + " " + display)

print 'Location: ' + get_param('ret', 'status')
print ''
