#!/usr/bin/python

from watchdog import *

wd = watchdog(form.getvalue("host"))
status = wd.process_status()

name = form.getvalue("proc")
if name == None:
    raise RuntimeError, "No process given"

if not status.has_key(name):
    raise RuntimeError, "No such process"

# Set up properties for subtitution in the template
props = status[name]
props["host"] = wd.host

if props["enabled"] == "1":
    props["enable_checked"] = "checked"
else:
    props["enable_checked"] = ""

if props["auto_display"] == "1":
    props["auto_display_checked"] = "checked"
else:
    props["auto_display_checked"] = ""

props['ret'] = get_param('ret', 'status')

# Fill in the template
template = open("edit.template")
for line in template:
    print line % props
