#!/usr/bin/python

from watchdog import *

group_name = form.getvalue('group')
if group_name == None:
    raise RuntimeError, 'No group specified'

group = process_groups[group_name]

cmd = form.getvalue('cmd')
arg = form.getvalue('arg')

if cmd == None:
    raise RuntimeError, 'No command specified'

for pg_host in group:
    # pg_host is a (host, [processes]) tuple
    
    host = pg_host[0]
    wd = watchdog(host)
    
    for proc in pg_host[1]:
        line = cmd + ' ' + escape(proc)
        if arg != None:
            line += ' ' + escape(arg)
        
        try:
            wd.command(line)
        except:
            pass
    
    wd.close()

print 'Location: ' + get_param('ret', 'groups')
print ''
