#!/usr/bin/python

from watchdog import *

wd = watchdog(form.getvalue('host'))

proc = form.getvalue('proc')

if proc == None:
    raise ValueError, 'No process specified'

wd.command('disable ' + escape(proc))

try:
    wd.command('signal ' + escape(proc) + ' 15')
except RuntimeError:
    # Since disable worked, this exception probably means that
    # the process is not running, which doesn't matter.
    pass

print 'Location: ' + get_param('ret', 'status')
print ''
