<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>rj_referee</name>
  <version>0.0.0</version>
  <description>TODO: Package description</description>
  <maintainer email="n8.wert.b@gmail.com">n8w3rt</maintainer>
  <license>TODO: License declaration</license>

  <depend>rclcpp</depend>
  <depend>boost</depend>
  <depend>fmt</depend>
  <depend>spdlog</depend>

  <depend>rj_common</depend>
  <depend>rj_constants</depend>
  <depend>rj_utils</depend>
  <depend>rj_msgs</depend>
  <depend>rj_protos</depend>
  <depend>rj_config_client</depend>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
