Import('*')

srcs = [
#	'main.cpp',  # don't include main here to allow for separate test and run executables
	'Processor.cpp',
	'Logger.cpp',
	'MainWindow.cpp',
	'ProtobufTree.cpp',
	'Joystick.cpp',
	'RefereeModule.cpp',
	'PlayConfigTab.cpp',
	'FieldView.cpp',
	'SimFieldView.cpp',
	'Configuration.cpp',
	'debug.cpp',
	'StripChart.cpp',
	'Robot.cpp',
	'VisionReceiver.cpp',

	'radio/SimRadio.cpp',
	'radio/USBRadio.cpp',

	'framework/Obstacle.cpp',
	'framework/Path.cpp',
	'framework/SystemState.cpp',
	'framework/RobotConfig.cpp',

# Sources for gameplay module

	# Core gameplay components',
	'gameplay/GameplayModule.cpp',
	'gameplay/Play.cpp',
	'gameplay/Behavior.cpp',
	'gameplay/Window.cpp',
	'gameplay/PreventDoubleTouch.cpp',

	# Planning components',
	'gameplay/planning/rrt.cpp',
	'gameplay/planning/Tree.cpp',
	'gameplay/planning/bezier.cpp',

	# Restart plays
	'gameplay/plays/OurKickoff.cpp',
	'gameplay/plays/TheirKickoff.cpp',
	'gameplay/plays/OurFreekick.cpp',
	'gameplay/plays/OurGoalKick.cpp',
	'gameplay/plays/OurCornerKick.cpp',
	'gameplay/plays/TheirFreekick.cpp',
	'gameplay/plays/KickPenalty.cpp',
	'gameplay/plays/DefendPenalty.cpp',
	'gameplay/plays/Stopped.cpp',
	
	# Open gameplay plays
	'gameplay/plays/MightyMight.cpp',
	'gameplay/plays/BasicOffense122.cpp',
	'gameplay/plays/BasicOffense121.cpp',
	'gameplay/plays/OpenField221.cpp',
	'gameplay/plays/YankOpen.cpp',
	'gameplay/plays/EmptyGoal.cpp',

  # Core behaviors
	'gameplay/behaviors/Move.cpp',
	'gameplay/behaviors/Capture.cpp',
	'gameplay/behaviors/Kickoff.cpp',
	'gameplay/behaviors/Penalty.cpp',
	'gameplay/behaviors/Idle.cpp',
	'gameplay/behaviors/Kick.cpp',
	'gameplay/behaviors/Mark.cpp',
	'gameplay/behaviors/Yank.cpp',
	'gameplay/behaviors/YankChip.cpp',
	'gameplay/behaviors/Fling.cpp',
	'gameplay/behaviors/LineKick.cpp',
	'gameplay/behaviors/PivotKick.cpp',
	'gameplay/behaviors/TouchKick.cpp',
	'gameplay/behaviors/Bump.cpp',
	'gameplay/behaviors/PassReceive.cpp',

	# Positions
	'gameplay/behaviors/positions/Goalie.cpp',
	'gameplay/behaviors/positions/Fullback.cpp',
	
	# Test framework for plays
	'gameplay/TestFixture.cpp',
	'gameplay/plays/test_plays/TestPathTracking.cpp',
	'gameplay/plays/test_plays/TestLatency.cpp',
	'gameplay/plays/test_plays/KickMeasurement.cpp',
	'gameplay/plays/test_plays/TestLineKick.cpp',
	

	# demo plays/behaviors
	'gameplay/plays/demo_plays/TestPlay.cpp',
	'gameplay/plays/demo_plays/FollowTheLeader.cpp',
	'gameplay/plays/demo_plays/PassPlay.cpp',
	'gameplay/plays/demo_plays/PassShootPlay.cpp',
	'gameplay/plays/demo_plays/LineUp.cpp',
	'gameplay/plays/demo_plays/MotionEval.cpp',
	'gameplay/plays/demo_plays/DemoPassing.cpp',
	'gameplay/plays/demo_plays/DemoAttack.cpp',
	'gameplay/plays/demo_plays/DemoCapture.cpp',
	'gameplay/plays/demo_plays/DemoYank.cpp',
	'gameplay/plays/demo_plays/DemoYankChip.cpp',
	'gameplay/plays/demo_plays/DemoFling.cpp',
	'gameplay/plays/demo_plays/DemoBump.cpp',
	'gameplay/plays/demo_plays/DemoLineAttack.cpp',
	'gameplay/plays/demo_plays/DemoPivotAttack.cpp',
	'gameplay/plays/demo_plays/DemoTouchKick.cpp',
	
	#Eric
	'gameplay/plays/demo_plays/DemoKickMeasurement.cpp',
	
#	'gameplay/plays/demo_plays/CalSpeed.cpp',

  # Mechanical tests
  'gameplay/plays/demo_plays/KickerEnduranceTest.cpp',

	# Tech Challenges
	'gameplay/plays/demo_plays/NavChallenge2011.cpp',
	'gameplay/plays/demo_plays/DynamicNavigationTC.cpp',

#	'gameplay/behaviors/test/MotionLeader.cpp',

# Sources for modeling module
	'modeling/BallTracker.cpp',
	'modeling/BallFilter.cpp',
	'modeling/RobotFilter.cpp',
	
#	'modeling/WorldModel.cpp',
#	'modeling/BallModel.cpp',
#	'modeling/RBPFBallModel.cpp',
#	'modeling/EKFBallModel.cpp',
#	'modeling/KalmanBallModel.cpp',      
#	'modeling/RobotModel.cpp',
#	'modeling/rbpf/Rbpf.cpp',
#	'modeling/rbpf/RbpfModel.cpp',
#	'modeling/rbpf/RbpfModelGraph.cpp',
#	'modeling/rbpf/RbpfState.cpp',
#	'modeling/rbpf/RbpfModelRolling.cpp',
#	'modeling/rbpf/RbpfModelKicked.cpp',
#	'modeling/kalman/difference_kalman.cpp',
#	'modeling/kalman/ExtendedKalmanFilter.cpp',

# Sources for motion module',
	'motion/MotionControl.cpp',
	
	'ui/main_icons.qrc',
	'ui/log_icons.qrc'
]

uics = env.Uic4([
	'ui/MainWindow.ui',
	'ui/PlayConfigTab.ui'
])

e = env.Clone()
e.Append(CPPPATH=['#/soccer', Dir('ui')])
e.Append(LIBS=['bfd', 'GLU'])

e.ParseConfig('pkg-config --cflags --libs libusb-1.0')

# build soccer executable
p = e.Program('soccer', ['main.cpp'] + srcs )
env.Depends(p, uics)
Default(e.Install(exec_dir, p))
Help('soccer: Main program\n')

# build log viewer executable 
p = e.Program('log_viewer', [
	'LogViewer.cpp',
	'FieldView.cpp',
	'ProtobufTree.cpp',
	'StripChart.cpp',
	'debug.cpp',
	'ui/log_icons.qrc'
])
env.Depends(p, env.Uic4('ui/LogViewer.ui'))
Default(e.Install(exec_dir, p))
Help('log_viewer: Stand-alone log viewer\n')

# build unit tests and framework
# Add new unit tests here
#tests = [
#	'tests/testExamples.cpp',
#	'tests/testPath.cpp',
#]
#e.Append(LIBS=['gtest']) # FIXME: binary library does not exist in later versions of gtest
## NOTE: this links against all sources to avoid needing to actually check dependencies
#p = e.Program('soccer_tests', ['tests/gtest_main.cpp'] + tests + srcs)
#Default(e.Install(exec_dir, p))
#test_alias = e.Alias('test', [p], p[0].abspath)
#AlwaysBuild(test_alias)
#Help('test: Run tests\n')
