#!/bin/bash -e

# Become root
if [ $UID -ne 0 ]; then
    echo "-- Becoming root"
    exec sudo $0
fi


BASE=$(readlink -f $(dirname $0)/..)

echo "-- Installing udev rules"
cp -f $BASE/util/robocup.rules /etc/udev/rules.d/

echo "-- Installing required packages"
pacman -S --needed --noconfirm $(sed 's/#.*//;/^$/d' $BASE/util/arch-packages.txt)

# required for scons
sudo pip2 install cffi pygit2

pip install -r $BASE/util/requirements3.txt
