#!/bin/sh
if [ "$1" = "--help" ]; then
    echo "Usage: $0 [<interface>]"
    echo "  Routes all multicast traffic to the given network interface"
    echo
    echo "  If <interface> is not given, the multicast route is deleted and"
    echo "  traffic is routed normally."
    echo
    exit 1
fi

echo "Deleting existing multicast route"
sudo route del -net 224.0.0.0 netmask 240.0.0.0 > /dev/null 2>&1
if [ -n "$1" ]; then
    echo "Adding multicast route to $1"
    sudo route add -net 224.0.0.0 netmask 240.0.0.0 $1 || exit 1
fi

