#!/bin/bash

# abort script if something fails
set -e

BASE="$(dirname $0)/.."

#  needed for the simulator
echo "-- Installing xquartz through homebrew cask"
brew cask install xquartz

echo "-- Installing required homebrew packages"
brew install $(sed 's/#.*//;/^$/d' $BASE/util/osx-packages.txt)

echo "-- Linking Qt 5 apps into /Applications"
brew linkapps qt5

echo "-- Installing python3 dependencies"
sudo pip3 install -r $BASE/util/requirements3.txt

# prevent OS X's AppNap "feature" from sleeping the simulator
echo "-- Disabling AppNap for simulator"
defaults write org.robojackets.robocup.simulator NSAppSleepDisabled -bool YES

echo "-- Updating submodules"
git submodule update --init
