#!/bin/bash

# abort script if something fails
set -e

BASE="$(dirname $0)/.."

#  needed for the simulator
echo "-- Installing xquartz through homebrew cask"
brew cask install xquartz

echo "-- Installing required homebrew packages"
brew install $(sed 's/#.*//;/^$/d' $BASE/util/osx-packages.txt)

echo "-- Linking Qt 5 apps into /Applications"
brew linkapps qt5

echo "-- Installing python3 dependencies"
sudo pip3 install -r $BASE/util/requirements3.txt

# prevent OS X's AppNap "feature" from sleeping the simulator
echo "-- Disabling AppNap for simulator"
defaults write org.robojackets.robocup.simulator NSAppSleepDisabled -bool YES

echo "-- Checking for libspnav for 3d mouse support"
SPNAV_LOC="/usr/local/include/spnav.h"
if [ ! -f "$SPNAV_LOC" ]; then
    echo "-- Downloading libspnav"
    TMP_DIR=$(mktemp -d /tmp/spacenav.XXXX)
    curl -L "http://downloads.sourceforge.net/project/spacenav/spacenav%20library%20%28SDK%29/libspnav%200.2.3/libspnav-0.2.3.tar.gz?r=&ts=1425162527&use_mirror=hivelocity" -o "$TMP_DIR/libspnav-0.2.3.tar.gz"
    pushd "$TMP_DIR"; tar -xvzf libspnav-0.2.3.tar.gz
    echo "-- Building and installing libspnav"
    pushd "$TMP_DIR/libspnav-0.2.3"; ./configure --disable-x11; make; sudo make install
    popd
    popd
fi

echo "-- Updating submodules"
git submodule update --init
