#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# By default this script does nothing.

route add 224.5.23.1 eth0 || true
route add 224.5.23.2 eth0 || true
route add 224.5.20.2 lo || true
route add 226.0.0.1 lo || true

exit 0
