#!/bin/bash -e

# Become root
if [ $UID -ne 0 ]; then
	echo "-- Becoming root"
	exec sudo $0
fi

MACH=$(uname -m)
unset DPKG_FLAGS

BASE=$(readlink -f $(dirname $0)/..)

if [ "$MACH" = "x86_64" ]; then
	echo "-- Detected a 64-bit system"

	# Make dpkg install 32-bit PhysX packages on a 64-bit system
	DPKG_FLAGS=--force-architecture

	# 32-bit compatibility (simulator must build as 32-bit for PhysX)
	echo "-- Installing 32-bit compatibility libraries"
	apt-get install libc6-dev-i386 g++-multilib ia32-libs
fi

echo "-- Installing normal packages"
apt-get install build-essential qt4-dev-tools libboost-dev \
	libusb-dev libblas-dev liblapack-dev libgtkmm-2.4-dev protobuf-compiler libprotobuf-dev \
	libpcap-dev scons graphviz

# Install all PhysX packages together
if [ ! -d /usr/lib/PhysX ]; then
	echo "-- Installing PhysX"
	dpkg -i $DPKG_FLAGS SoccSim/lib/physx/*.deb
else
	echo "-- PhysX is already installed"
fi

