#!/bin/bash -e

HELP_STR="Usage: ./ubuntu-setup [-y | --yes] [-n | --noclobber] [-c | --clobber] [-f | --firmware] [-nf | --nofirmware] [-osl | --overwrite-sources-list ] [-h | --help]

\tyes:\t\t\tassume no user input
\tnoclobber:\t\tdont install 3rd party repositories
\tclobber:\t\tInstall 3rd party repositories
\tfirmware:\t\tInstall firmware repository
\tnofirmware:\t\tPrevents installation of firmware deps firmware repository
\toverwrite-sources-list:\tOverwrites the sources.list with gatech mirrors for faster ubuntu-setup. Only works on ubuntu > precise.
\thelp:\t\t\tprint this message!

This script will need root privileges"

DISTRO_STR="The linux distro you are using is not supported by ubuntu-setup. Please file an issue if you want to request your debian based distro to be added."

# defaults!
OVERWRITE_SOURCES=false
YES=false
SYSTEM="unknown"
NO_SUBMODULES=false

BASE=$(readlink -f $(dirname $0)/..)

if cat /etc/os-release | grep -iq '^NAME=.*Debian'; then # don't add repositories on debian, unsupported
    echo "[WARN] You are using a flavor of debian. This configuration is not officially supported..." >&2
    SYSTEM="debian"
    ADD_REPOS=false
elif cat /etc/os-release | grep -iq '^NAME=.*Ubuntu'; then # We are using a version of ubuntu...
    if cat /etc/os-release | grep -iq '^VERSION=.*22.04'; then # Using Ubuntu 20.04
        echo "Ubuntu 22.04 Detected..."
        SYSTEM="ubuntu-22.04"
        ADD_REPOS=false
    else
        echo "Sorry, we only support 22.04 due to ROS2." >&2
        echo "$DISTRO_STR" >&2
        exit 1
    fi
else
    echo "$DISTRO_STR" >&2
    exit 1
fi

# parse command line args
for i in "$@"
do
    case $i in
        -y|--yes)
            YES=true
            ;;
        -n|--noclobber)
            # This option omits the addition of the 3rd party repos
            ADD_REPOS=false
            ;;
        -c|--clobber)
            # This option forces addition of the custom repos
            ADD_REPOS=true
            ;;
        -osl|--overwrite-sources-list)
            # This option overwrites the sources list for faster downloads
            OVERWRITE_SOURCES=true
            ;;
        -h|--help)
            echo -e "$HELP_STR"
            exit 1
            ;;
        --no-submodules)
            # only for CI
            NO_SUBMODULES=true
            ;;
        *)
            echo "Unrecognized Option: $i"
            echo -e "\n$HELP_STR"
            exit 1
            # unknown options
            ;;
    esac
done

# Become root
if [ $UID -ne 0 ]; then
	echo "-- Becoming root"
	exec sudo $0 $@
fi

# Add the llvm key
# Fingerprint: 6084 F3CF 814B 57C1 CF12 EFD5 15CF 4D18 AF4F 7421
sudo apt-get update && sudo apt-get install $ARGS lsb-release wget software-properties-common gnupg locales -y # Somehow we don't have wget

if $OVERWRITE_SOURCES; then
    read -p "Do you really want to overwrite your sources.list? THIS SHOULD ONLY BE DONE ON STOCK UBUNTU [yN]: " yn
    case $yn in
        [Yy]* ) ;;
        [Nn]* ) exit;;
        * ) exit ;;
    esac

    # Copy sources.list to sources.list.old if sources.list.old is empty
    if [ -f "/etc/apt/sources.list" ]; then
        cp -n /etc/apt/sources.list /etc/apt/sources.list.old
    else
        echo "A prior /etc/apt/sources.list was not found! This probably means you are on a non-debian based system! To force override, run: touch /etc/apt/sources.list" 1>&2
        exit 1
    fi

    # Cross our fingers...
    sed -i 's%^\s*\([^#]\S\+\)\s\+\S\+%\1 mirror://mirrors.ubuntu.com/mirrors.txt%' /etc/apt/sources.list
EOF

fi

if $ADD_REPOS; then
    # add repo for backport of cmake3 from debian testing
    # TODO remove this once ubuntu ships cmake3
    # sudo add-apt-repository -y ppa:george-edison55/cmake-3.x

    # for newer compilers
    add-apt-repository -y ppa:ubuntu-toolchain-r/test
fi

# if yes option is checked, add  a -y
ARGS=""
if $YES; then
    ARGS="-y"
fi

# Somehow 16.04 doesn't support https
wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -

# Install clang-format-10 using automatic llvm installation script
if [ "$SYSTEM" = "ubuntu-22.04" ]; then
    wget https://apt.llvm.org/llvm.sh
    chmod +x llvm.sh
    sudo ./llvm.sh 16
    rm llvm.sh
fi

# Add ROS 2 Humble key and repo
if [[ ! $(which ros2) ]]; then
    sudo locale-gen en_US en_US.UTF-8
    sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
    export LANG=en_US.UTF-8
    sudo add-apt-repository universe
    sudo apt update && sudo apt install curl -y
    export ROS_APT_SOURCE_VERSION=$(curl -s https://api.github.com/repos/ros-infrastructure/ros-apt-source/releases/latest | grep -F "tag_name" | awk -F\" '{print $4}')
    curl -L -o /tmp/ros2-apt-source.deb "https://github.com/ros-infrastructure/ros-apt-source/releases/download/${ROS_APT_SOURCE_VERSION}/ros2-apt-source_${ROS_APT_SOURCE_VERSION}.$(. /etc/os-release && echo $VERSION_CODENAME)_all.deb" # If using Ubuntu derivates use $UBUNTU_CODENAME
    sudo dpkg -i /tmp/ros2-apt-source.deb
fi


# Install eloquent for 18.04, foxy for 20.04
if [ "$SYSTEM" = "ubuntu-22.04" ]; then
    sudo apt-get update && sudo apt-get install -y ros-humble-desktop ros-dev-tools
fi

MACH=$(uname -m)
unset DPKG_FLAGS

echo "-- Installing required packages"

PACKAGES="$(sed 's/#.*//;/^$/d' $BASE/util/ubuntu-packages.txt)"

# install all of the packages listed in required_packages.txt
apt-get install $ARGS $PACKAGES

# install python3 requirements
python3 -m pip install pip==22.1
pip3 install -r $BASE/util/requirements3.txt
