#!/bin/bash -e

# Become root
if [ $UID -ne 0 ]; then
	echo "-- Becoming root"
	exec sudo $0
fi

# add repo for backport of cmake3
# TODO remove this once ubuntu ships cmake3
apt-add-repository -y ppa:andykimpe/cmake3

#TODO dont run this if running cmake3. This dosent hurt for now
apt-get -y purge cmake
# apt get install cmake3 is taken care of by requiremnets.
# When removing this, change cmake3 to cmake in dependencies

apt-get update

MACH=$(uname -m)
unset DPKG_FLAGS

BASE=$(readlink -f $(dirname $0)/..)

echo "-- Installing udev rules"
cp -f $BASE/util/robocup.rules /etc/udev/rules.d/

echo "-- Installing required packages"
# install all of the packages listed in required_packages.txt
apt-get install $(sed 's/#.*//;/^$/d' $BASE/util/ubuntu-packages.txt)

# install python3 requirements
pip3 install -r $BASE/util/requirements3.txt
