set(_AMENT_PACKAGE_NAME "rj_msgs")
set(rj_msgs_VERSION "0.0.0")
set(rj_msgs_MAINTAINER "Kyle Stachowicz <kylestach99@gmail.com>, Oswin So <oswinso@gmail.com>")
set(rj_msgs_BUILD_DEPENDS "std_msgs" "rj_geometry_msgs")
set(rj_msgs_BUILDTOOL_DEPENDS "ament_cmake" "rosidl_default_generators")
set(rj_msgs_BUILD_EXPORT_DEPENDS "std_msgs" "rj_geometry_msgs")
set(rj_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(rj_msgs_EXEC_DEPENDS "std_msgs" "rj_geometry_msgs")
set(rj_msgs_TEST_DEPENDS )
set(rj_msgs_GROUP_DEPENDS )
set(rj_msgs_MEMBER_OF_GROUPS "rosidl_interface_packages")
set(rj_msgs_DEPRECATED "")
set(rj_msgs_EXPORT_TAGS)
list(APPEND rj_msgs_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
