/radio:
  ros__parameters:
    timeout: 0.25
    use_sim_time: false
    # output port from field comp's perspective
    server_port: 25564
    # IP address will auto-latch to Ubiquiti cloud key's IP per UDP v4 protocol
    # (as in, the field comp simply broadcasts on the Ubiquiti on server_port)

/vision_receiver:
  ros__parameters:
    port: 10006
    hz: 120.0
    use_sim_time: false
    # vision_interface: "" # will auto-latch to kSharedVisionAddress

