/radio:
  ros__parameters:
    timeout: 0.25
    use_sim_time: false
    # interface: "172.16.1.1"

/vision_receiver:
  ros__parameters:
    port: 10006
    hz: 120.0
    use_sim_time: false
    interface: "" # will auto-latch to kSharedVisionAddress
