Import('*')

usb = env.Clone()
usb.Append(LIBS='usb')

p = usb.Program('radio', [
	'main.cpp',
	'USB_Device.cpp',
	'Radio.cpp'])

Default(usb.Install(exec_dir, p))
Help('radio: Base station interface\n')
