#include "spi.h"

void spi_init() {
    AT91C_BASE_PMC->PMC_PCER = 1 << AT91C_ID_SPI;
    AT91C_BASE_SPI->SPI_CR = AT91C_SPI_SWRST;
    AT91C_BASE_SPI->SPI_CR = AT91C_SPI_SWRST;
    AT91C_BASE_SPI->SPI_MR = AT91C_SPI_MSTR | AT91C_SPI_MODFDIS;
    AT91C_BASE_SPI->SPI_CSR[NPCS_FLASH] =
        (4 << 8) | AT91C_SPI_BITS_8 | AT91C_SPI_CSAAT | AT91C_SPI_NCPHA;
    AT91C_BASE_SPI->SPI_CSR[NPCS_FPGA] =
        (12 << 8) | AT91C_SPI_BITS_8 | AT91C_SPI_CSAAT | AT91C_SPI_NCPHA;
    AT91C_BASE_SPI->SPI_CSR[NPCS_RADIO] =
        (12 << 8) | AT91C_SPI_BITS_8 | AT91C_SPI_CSAAT | AT91C_SPI_NCPHA;
    AT91C_BASE_SPI->SPI_CR = AT91C_SPI_SPIEN;
    AT91C_BASE_PIOA->PIO_ASR = FLASH_NCS | MISO | MOSI | SCK;
    AT91C_BASE_PIOA->PIO_BSR = RADIO_NCS | FPGA_NCS;
    AT91C_BASE_PIOA->PIO_PDR =
        FLASH_NCS | FPGA_NCS | RADIO_NCS | MISO | MOSI | SCK;
}

void spi_shutdown() {
    AT91C_BASE_PIOA->PIO_ODR =
        FLASH_NCS | FPGA_NCS | RADIO_NCS | MISO | MOSI | SCK;
    AT91C_BASE_PIOA->PIO_PER =
        FLASH_NCS | FPGA_NCS | RADIO_NCS | MISO | MOSI | SCK;
}

uint8_t spi_xfer(uint8_t tx) {
    while (!(AT91C_BASE_SPI->SPI_SR & AT91C_SPI_TDRE))
        ;
    AT91C_BASE_SPI->SPI_TDR = tx;
    while (!(AT91C_BASE_SPI->SPI_SR & AT91C_SPI_RDRF))
        ;
    return AT91C_BASE_SPI->SPI_RDR;
}

void spi_select(int n) {
    AT91C_BASE_SPI->SPI_MR =
        (AT91C_BASE_SPI->SPI_MR | AT91C_SPI_PCS) & ~(1 << (16 + n));
}
