#!/usr/bin/env python

import sys
import find_tty
from sam7 import *

devices = find_tty.find(0x03eb, 0x6124)
if not devices:
	print >> sys.stderr, 'No SAM7 devices found'
	sys.exit(1)

sam = SAM7(devices[0])
print sam.version()

if len(sys.argv) != 2:
	print >> sys.stderr, 'Usage: %s <filename.bin>' % sys.argv[0]
	sys.exit(1)

f = file(sys.argv[1])
data = f.read()
f.close()

sam.writeData(0x202000, data)
print 'Go'
sam.go(0x202000)
