#!/bin/bash

source $HOME/.bashrc

# Get the directory containing this script.
WATCHDOG_DIR=$(readlink -f $(dirname $BASH_SOURCE))

export DISPLAY=:0
$WATCHDOG_DIR/cpp/build/watchdog $WATCHDOG_DIR/watchdog.xml > /dev/null 2>&1 &

