<?xml version="1.0"?>
<package format="3">
  <name>rj_param_utils</name>
  <version>0.1.0</version>
  <description>Utilities for managing ROS 2 parameters</description>
  <maintainer email="hello@robojackets.org">RoboCup Software Team, RoboJackets</maintainer>
  <license>Apache-2.0</license>

  <!-- Build system -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- Dependencies -->
  <depend>rclcpp</depend>

  <!-- Test dependencies -->
  <test_depend>ament_cmake_gtest</test_depend>
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
