#!/usr/bin/env python

import io
import sys
import find_tty

devices = find_tty.find(0x03eb, 0x6119)
if not devices:
	print >> sys.stderr, 'USB device not found'
	sys.exit(1)

if len(sys.argv) != 2:
	print >> sys.stderr, 'Usage: %s <file>' % sys.argv[0]
	sys.exit(1)

def read_exactly(f, n):
	data = ''
	while n:
		x = f.read(n)
		data += x
		n -= len(x)
	return data

f = file(sys.argv[1])
data = f.read()
f.close()

f = io.open(devices[0], 'w+b', 0)

print 'Erasing'
cmd = 'spi_erase\r'
f.write(cmd)
result = read_exactly(f, len(cmd) + 3)
if result != cmd + '\n> ':
	print 'Bad echo: %s' % result
	sys.exit(1)

print 'Writing'
cmd = 'spi_write 0 0x%x\r' % len(data)
f.write(cmd)
result = read_exactly(f, len(cmd) + 1)
if result != cmd + '\n':
	print 'Bad echo: %s' % result
	sys.exit(1)

f.write(data)

result = read_exactly(f, 6)
if result != 'OK\r\n> ':
	print 'Bad result: %s' % result
	sys.exit(1)

print 'Verifying'
cmd = 'spi_read 0 0x%x\r' % len(data)
f.write(cmd)
result = read_exactly(f, len(cmd) + 1)
if result != cmd + '\n':
	print 'Bad echo: "%s"' % result
	sys.exit(1)
v = read_exactly(f, len(data))
if v == data:
	print 'OK'
else:
	f = file('spi_verify.bad', 'wb')
	f.write(v)
	f.close()
	print 'Verification failed!'
	print 'Returned data written to spi_verify.bad'
