Import('*')

avr_usb = avr.Clone()
avr_usb.Append(DEVICE='at90usb1287')
avr_usb.Append(CFLAGS='-mmcu=${DEVICE}')
avr_usb.Append(LINKFLAGS='-mmcu=${DEVICE}')

avr_usb.Program('base_station.elf',
	['base_station.c',
	'radio.c',
	'device.c',
	'host.c'])

avr_usb.Binary('base_station.bin', 'base_station.elf')

avr_usb.Alias('base-prog', 'base_station.bin', Action('dfu-programmer ${DEVICE} erase && dfu-programmer ${DEVICE} flash --suppress-validation ${SOURCE} && dfu-programmer ${DEVICE} reset'))
avr_usb.AlwaysBuild('base-prog')

