name: Docker CI Image Deployment

on:
  push:
    branches: [ "ros2" ]
    paths:
      - 'Dockerfile.ci'
      - 'util/ubuntu-setup'
      - 'util/ubuntu-packages.txt'
      - 'util/requirements3.txt'
  workflow_dispatch: 

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile.ci --tag robojackets/robocup-software:humble

      - name: Push the Docker image
        run: |
          docker push robojackets/robocup-software:humble
