
Import('*')


e = env.Clone()

e.Append(LIBS=['boost_python-py33'])
e.Append(CPPPATH=['#/soccer'])
e.ParseConfig('pkg-config --cflags python3')

# name the output 'robocup.so', not 'librobocup.so'
# env['ENV']['SHLIBPREFIX'] = ''

pymod = e.SharedLibrary('robocup', ['robocup.cpp'], SHLIBPREFIX='')
Default(e.Install(exec_dir, pymod))
Help('Python module that lets the high-level stuff interact with the C++ side of things')
